### ISSUE TITLE
Better documentation for the config file

### ISSUE THREAD

**Issue by frisso** [netgroup-polito/frog4-openflow-do#1]
Specify the allowed options in the following items:
controller_name = ...
odl_version= ...

Document more the following items:
- What does "oo" mean in the command "oo_console_print"? Which console are we referring to?

Rename following item:
- dump_file ==> database_name

**Comment by frisso** [comment]
@giacomoratta

**Comment by giacomoratta** [comment]
Done!

Commit > https://github.com/netgroup-polito/frog4-openflow-do/commit/f4df9cf17edc7c47344aaf60b21c13aa0fb85331
