### ISSUE TITLE
Missing update for exported resources

### ISSUE THREAD

**Issue by frisso** [netgroup-polito/frog4-openflow-do#2]
Currently the openflow-DO reads the local file that tells which resources are available.
However, if those resources change (e.g., a VLAN is used in an endpoint), their description is not updated and re-sent to the message broker.
This creates troubles for the upper layer orchestrator, as it cannot know which resources have already been consumed, hence some decisions may be wrong.

**Comment by giacomoratta** [comment]
Resource description updates ... 6f814c2f6b7c0701c5f3fe614093b03f2dc3ceb3
